using SeekClaw.Runtime.Configuration;

namespace SeekClaw.Tests;

public sealed class ConfigTests : IDisposable
{
    private readonly string _dir = Path.Combine(Path.GetTempPath(), "seekclaw-tests", Guid.NewGuid().ToString("N"));

    public ConfigTests() => Directory.CreateDirectory(_dir);

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch (IOException) { }
    }

    private ConfigStore NewStore() => new(
        Path.Combine(_dir, "config.json"),
        Path.Combine(_dir, "state.json"));

    [Fact]
    public void MissingConfig_CreatesDefaults_AndPersists()
    {
        var store = NewStore();
        Assert.Equal("default", store.Config.ActiveProfile);
        Assert.True(File.Exists(Path.Combine(_dir, "config.json")));

        // First-run seed is generated by serializing the code-defined defaults.
        Assert.Contains(store.Config.Providers, p => p.Id == "anthropic" && p.Kind == "anthropic");
        Assert.Contains(store.Config.Providers, p => p.Id == "openai");
        Assert.Contains(store.Config.Providers, p => p.Id == "ollama" && !p.Enabled);
        Assert.Equal(
            new[] { "anthropic/claude-sonnet-5", "openai/gpt-5.5", "google/gemini-2.5-pro", "mimo/mimo-v2-pro" },
            store.Config.Routing.Strategies["balanced"]);
        Assert.Equal(40, store.Config.Agent.MaxSteps);
    }

    [Fact]
    public void SaveAndReload_RoundTripsProvidersAndProfiles()
    {
        var store = NewStore();
        store.Config.Providers.Add(new ProviderConfig
        {
            Id = "test",
            Kind = "openai",
            BaseUrl = "https://example.test/v1",
            ApiKey = "config-secret",
            Models = [new ModelConfig { Id = "m1", Alias = "one", ContextWindow = 9000, InputPricePerMTok = 1.5m }],
        });
        store.Config.Profiles["work"] = new ProfileConfig { Provider = "test", Model = "m1", Temperature = 0.3 };
        store.Save();

        var reloaded = NewStore();
        var provider = Assert.Single(reloaded.Config.Providers, p => p.Id == "test");
        Assert.Equal("test", provider.Id);
        Assert.Equal("config-secret", provider.ApiKey);
        Assert.Equal(9000, provider.Models[0].ContextWindow);
        Assert.Equal("one", provider.Models[0].Alias);
        Assert.Equal(1.5m, provider.Models[0].InputPricePerMTok);
        Assert.Equal(0.3, reloaded.Config.Profiles["work"].Temperature);
    }

    [Fact]
    public void CorruptConfig_FallsBackToDefaults()
    {
        File.WriteAllText(Path.Combine(_dir, "config.json"), "{ not json !!");
        var store = NewStore();
        Assert.Equal("default", store.Config.ActiveProfile);
    }

    [Fact]
    public void ResolveApiKey_UsesOnlyExplicitConfigurationValue()
    {
        Environment.SetEnvironmentVariable("SEEKCLAW_TEST_KEY", "from-env");
        try
        {
            Assert.Null(new ProviderConfig().ResolveApiKey());
            Assert.Equal("direct", new ProviderConfig { ApiKey = "direct" }.ResolveApiKey());
        }
        finally
        {
            Environment.SetEnvironmentVariable("SEEKCLAW_TEST_KEY", null);
        }
    }
}
